# Test against the latest version of this Node.js version
environment:
  nodejs_version: "6"
  GH_TOKEN:
    secure: LiI5jyuHUw6XbH4kC3gP1HX4P/v4rwD/gCNtaFhQu2AvJz1/1wALkp5ECnIxRySN

skip_branch_with_pr: true

clone_folder: C:\projects\lbry-electron

# Install scripts. (runs after repo cloning)
install:
  # needed to deal with submodules
  - git submodule update --init --recursive
  - python build\set_version.py
  - python build\set_build.py
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install
  - cd app
  - npm install
  - cd ..
  # create daemon and cli executable
  - cd daemon
  - ps: .\build.ps1
  - cd ..
  # build ui
  - cd ui
  - npm install
  - node_modules\.bin\node-sass --output dist\css --sourcemap=none scss\
  - node_modules\.bin\webpack
  - ps: Copy-Item dist ..\app\ -recurse
  - cd ..
  # copy executables into ui
  - ps: Copy-Item daemon\dist\lbrynet-daemon.exe app\dist
  - ps: Copy-Item daemon\dist\lbrynet-cli.exe app\dist

build_script:
  # build electron app
  - node_modules\.bin\build -p never
  # for debugging, see what was built
  - python build\zip_daemon.py
  - dir dist
  - pip install -r build\requirements.txt
  - python build\release_on_tag.py

test: off

artifacts:
  - path: dist\*.exe
    name: LBRY

  - path: dist\*.zip
    name: lbrynet-daemon
